BasicFile = Statements
Statements = (Statement NEWLINE)* Statement [NEWLINE]
<Statement> = Print
Print = <"PRINT"> SPACE Expression
<Expression> = NumberLiteral | StringLiteral | Identifier
NumberLiteral = #"[0-9]+"
StringLiteral = <'"'> #'[^"]*' <'"'>
Identifier = #"[a-zA-Z]+"

<SPACE> = <" "+>
<NEWLINE> = <"\n">
